# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ns3-nested-structure-example', ['ns3-nested-structure'])
    obj.source = 'ns3-nested-structure-example.cc'

